### ISSUE TITLE
 Build for selendroid-standalone - 4 test cases are failing.

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium-uiautomator2-driver#1]
```
AbstractDeviceTest. testGetCrashLogContents
AbstractDeviceTest. testListThirdPartyProcesses
DefaultAndroidEmulatorTests. testShouldBeAbleToStartEmulator
DefaultHardwareDeviceTests. testShouldBeAbleToStartSelendroid
```

**Comment by bootstraponline** [comment]
How are you running the test cases?

`gradle clean connectedCheck`?

**Comment by vishals79** [comment]
These test cases are getting executed while building the selendroid-standalone project using
gradle build

[AbstractDeviceTest.pdf](https://github.com/appium/appium-uiautomator2-driver/files/7469/AbstractDeviceTest.pdf)
[DefaultAndroidEmulatorTests.pdf](https://github.com/appium/appium-uiautomator2-driver/files/7467/DefaultAndroidEmulatorTests.pdf)
[DefaultHardwareDeviceTests.pdf](https://github.com/appium/appium-uiautomator2-driver/files/7468/DefaultHardwareDeviceTests.pdf)

**Comment by PrakashGoulla** [comment]
Build works fine with `gradle clean connectedCheck`, however I do not see any tests being executed from selendroid-standalone server.

**Comment by PrakashGoulla** [comment]
Looks like maven project is somehow skipping/not executing any tests from the following test files.

`DefaultAndroidEmulatorTests`
`DefaultHardwareDeviceTests`

**Comment by bootstraponline** [comment]
> connectedCheck is only for android projects?

Right, `connectedCheck` is android only so it wouldn't apply to selendroid-standalone. 

I'll look into the `gradle test` failures. If the same tests fail and/or aren't executed when using `mvn test` then it's probably safe to ignore them.

**Comment by bootstraponline** [comment]
Selendroid doesn't even build correctly for me via maven.


```
$ ./third-party/mvnInstall.sh
$ mvn clean package
```

```
[INFO] selendroid ........................................ SUCCESS [0.148s]
[INFO] android-driver-app ................................ SUCCESS [5.414s]
[INFO] selendroid-server-common .......................... SUCCESS [2.363s]
[INFO] selendroid-server ................................. FAILURE [2.368s]
[INFO] selendroid-grid-plugin ............................ SKIPPED
[INFO] selendroid-common ................................. SKIPPED
[INFO] selendroid-standalone ............................. SKIPPED
[INFO] selendroid-client ................................. SKIPPED
[INFO] selendroid-test-app ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by bootstraponline** [comment]
Ok. I reproduced the failure via `gradle test`.

```
:selendroid-standalone:test

io.selendroid.standalone.android.impl.AbstractDeviceTest > testListThirdPartyProcesses FAILED
    java.lang.NullPointerException at AbstractDeviceTest.java:81

io.selendroid.standalone.android.impl.AbstractDeviceTest > testGetCrashLogContents FAILED
    java.lang.NullPointerException at AbstractDeviceTest.java:59

io.selendroid.standalone.android.impl.DefaultAndroidEmulatorTests > testShouldBeAbleToStartEmulator FAILED
    java.lang.AssertionError at DefaultAndroidEmulatorTests.java:42

io.selendroid.standalone.android.impl.DefaultHardwareDeviceTests > testShouldBeAbleToStartSelendroid FAILED
    io.selendroid.server.common.exceptions.SelendroidException at DefaultHardwareDeviceTests.java:57

81 tests completed, 4 failed, 3 skipped
:selendroid-standalone:test FAILED

FAILURE: Build failed with an exception.
```

**Comment by bootstraponline** [comment]
I debugged and fixed [one of the failures](https://github.com/appium/appium-uiautomator2-driver/pull/3). As far as I can tell the original tests are written incorrectly and need to be updated. I commented upstream to clarify if this is indeed the situation.

**Comment by bootstraponline** [comment]
@lukeis was kind enough to debug the issue and it's due to using newer versions of dependencies (commons-exec). The fix is to update the tests so they pass. I'll add this to my to do list.
