### ISSUE TITLE
Update to com.android.tools.build:gradle:1.4.0-beta5

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium-uiautomator2-driver#2]
[beta5](https://bintray.com/android/android-tools/com.android.tools.build.gradle/view) was released yesterday.

**Comment by vishals79** [comment]
Updated build system to 1.4.0-beta5

**Comment by bootstraponline** [comment]
https://github.com/appium/appium-uiautomator2-driver/commit/a54e1be27c15f7e5a12fb2dc03285896269c4e1c
