### ISSUE TITLE
Few test case are failing when executing multiple test case with uiautomator2-driver

### ISSUE THREAD

**Issue by KumarNellore** [appium/appium-uiautomator2-driver#38]
Though failing test case are working fine with older version of appium.

### Steps followed :
-  Updated capability as below:
```
capability.setCapability(MobileCapabilityType.AUTOMATION_NAME, "uiautomator2");
```
-  Started appium from command line.
-  Set the url to http://127.0.0.1:4723/wd/hub.

### Extra detail:
- [x] Device Platform: Android
- [x] automationName: uiautomator2
- [x] Java version: 1.8.0_73

This is reproducible when running multiple test case .

### Attaching log file for reference.

[logcat.txt](https://github.com/appium/appium-uiautomator2-driver/files/529006/logcat.txt)
[nodeLog.txt](https://github.com/appium/appium-uiautomator2-driver/files/529007/nodeLog.txt)

[InternalServerError.txt](https://github.com/appium/appium-uiautomator2-driver/files/529343/InternalServerError.txt)

### Sample error message:
An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 78 milliseconds For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26' System info: host: '<hostname>', ip: '<ipaddress>', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_73' Driver info: io.appium.java_client.android.AndroidDriver Capabilities [{app=F:\appium\newsdqa\testsdqa\sdqa\src\test\resources\com.<testapp>.main-2.apk, newCommandTimeout=0, automationName=uiautomator2, platformName=Android, deviceName=<devicename>, platform=ANY}] Session ID: d62abbb7-c2af-4bc1-be23-76c0a5440b35 *** Element info: {Using=id, value=com.<testapp>.main:id/<title>}

**Comment by sravanmedarapu** [comment]
@KumarNellore, Can you share more info.

Please make sure they are not false failures with sync issues.

**Comment by KumarNellore** [comment]
Yes @sravanmedarapu  it look like sync issue. In debug mode i'm able to see element.
