### ISSUE TITLE
Implicit wait is not working in uiautomator2-driver

### ISSUE THREAD

**Issue by KumarNellore** [appium/appium-uiautomator2-driver#39]
Please find below appium log :
[debug] [BaseDriver] Waiting up to 20000 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/9348725d-80d7-4900-a21d-b8fea7c3d592/element] with body: {"strategy":"id","selector"...
[HTTP] <-- POST /wd/hub/session/c51a777c-cfc9-4749-a775-d7302b120387/element 500 105 ms - 164

**Comment by sravanmedarapu** [comment]
Using `appium-uiautomator2-driver v0.0.6` should fix the issue.

**Comment by KumarNellore** [comment]
@sravanmedarapu Tested in version 0.0.6 its working fine. Thanks for fixing it 👍
