### ISSUE TITLE
Sending integer using sendKeys 

### ISSUE THREAD

**Issue by anniegandhi** [appium/appium-uiautomator2-driver#450]
I am not able to type integer value using function sendKeys . It is only accepting string .
Is there any way for the same or should I use some other method for the same.

Please help

**Comment by KazuCocoa** [comment]
Do you mean client side stuff?
A client cannot accept an integer. (And the client converts it to string to sent it to Appium)

**Comment by anniegandhi** [comment]
Hi ,

I am talking about below error.


Did not get confirmation UiAutomator2 deleteSession worked; Error was:
UnknownError: An unknown server-side error occurred while processing the
command. Original error: Could not proxy command to the remote server.
Original error: socket hang up.


I am not sending any integer value anywhere . Could you please help
elaborate.

Will be really helpful!

**Comment by KazuCocoa** [comment]
Potentially it could be more general issue.

Could you create a new issue in with filling out its template?
https://github.com/appium/appium/issues/new

Then, with adb logcat helps us to detect the cause.

**Comment by anniegandhi** [comment]
Hi ,

I have created a new issue in the template . Please let me know if some
more details need to be needed.

https://github.com/appium/appium/issues/15270

Regards,
Aashima

**Comment by KazuCocoa** [comment]
thanks
