### ISSUE TITLE
create an appium 2 driver script to clean device artifacts

### ISSUE THREAD

**Issue by jlipps** [appium/appium-uiautomator2-driver#542]
One common problem driver users encounter is old or stale Appium-related artifacts on a device, things like:

- the uia2 server
- the appium settings app
- something else i can't remember

We often encounter these issues in issue reports and provide a long list of commands to run to uninstall these artifacts. We could wrap up this logic as a driver script and document it as a troubleshooting step, saving ourselves and users time. It could look like one of these options from a user perspective, for example:

- `appium driver run uiautomator2 clean`
- `appium driver run uiautomator2 reset`
- `appium driver run uiautomator2 clear-artifacts`

Then the adb scripts would be run under the hood (perhaps via our ADB library for robustness)

**Comment by mykola-mokhnach** [comment]
`appium driver run uiautomator2 reset` script works as expected
