### ISSUE TITLE
In android getting list item issue 

### ISSUE THREAD

**Issue by VijayRathodM** [appium/appium-uiautomator2-driver#586]
in android how to get all list items because some items are invisible on the screen, so all items text is not getting any solution?

**Comment by KazuCocoa** [comment]
Possible way we could suggest is https://github.com/appium/appium-uiautomator2-driver#elements-cannot-be-found

**Comment by KazuCocoa** [comment]
https://discuss.appium.io/ may also help to ask such questions

**Comment by noahgregory-cigna** [comment]
If you are using `FlatList` in React Native. Try setting the `removeClippedSubviews` prop to `false`.
