### ISSUE TITLE
Why add npm-shrinkwrap.json to npm package?

### ISSUE THREAD

**Issue by yanhaijing** [appium/appium-uiautomator2-driver#642]
Can someone tell me why this file was added?
<img width="246" alt="image" src="https://github.com/appium/appium-uiautomator2-driver/assets/3192087/2f0069c7-49db-45f1-866a-38fd8f0d233b">

Adding this file will cause the dependency to not be hoist.

<img width="264" alt="image" src="https://github.com/appium/appium-uiautomator2-driver/assets/3192087/61360167-20a8-4595-9684-fa18b395bf41">

**Comment by KazuCocoa** [comment]
It is to lock the dependencies' version

**Comment by yanhaijing** [comment]
When used with appium-chromium-driver, it will cause appium-chromedriver to install two copies.
Because appium-chromium-driver also adds npm-shrinkwrap.json.
```
appium-chromium-driver
└──node_modules
           └──appium-chromedriver
appium-uiautomator2-driver
└──node_modules
           └──appium-chromedriver
```

**Comment by jlipps** [comment]
It's typically expected that separate appium drivers have their own entirely different dependency tree anyway. Are you wanting to install them both in the same node project?

**Comment by yanhaijing** [comment]
For this example, appium-chromium-driver and appium-uiautomator2-driver refer to appium-chromedriver is different. Isn't that a bug?

> When used with appium-chromium-driver, it will cause appium-chromedriver to install two copies.与 appium-chromium-driver 一起使用时，会导致 appium-chromedriver 安装两份。 Because appium-chromium-driver also adds npm-shrinkwrap.json.因为appium-chromium-driver还添加了npm-shrinkwrap.json。
> 
> ```
> appium-chromium-driver
> └──node_modules
>            └──appium-chromedriver
> appium-uiautomator2-driver
> └──node_modules
>            └──appium-chromedriver
> ```
> 
> I use Node v16.17.0, npm 8.15.0, package-lock.json lockfileVersion 2我使用 Node v16.17.0、npm 8.15.0、package-lock.json lockfileVersion 2

**Comment by KazuCocoa** [comment]
no, it isn't a bug since `appium-chromium-driver` and `appium-uiautomator2-driver` dependencies can be different.

For example, when a user installs old `appium-chromium-driver` and newser `appium-uiautomator2-driver`, these chromedriver could be different versions. `appium-chromedriver` installed by `appium-chromium-driver` can have incompatibility with what `appium-uiautomator2-driver` needs.
