### ISSUE TITLE
mobile: deepLink is not implemented

### ISSUE THREAD

**Issue by wazzeps** [appium/appium-uiautomator2-driver#666]
Appium 2.1.3
uiautomator2@2.31.2

[debug] [AndroidUiautomator2Driver@e799 (a5f4b33a)] Calling AppiumDriver.execute() with args: ["mobile:deepLink",[{"url":"https://someurl.com/e/LwzvrUc","package":"some.package.android.beta"}],"a5f4b33a-481c-4207-9a8f-57d4d81cb3af"]
[debug] [AppiumDriver@9e26] Clearing new command timeout pre-emptively since plugin(s) will handle this command
[AppiumDriver@9e26] Plugins which can handle cmd 'execute': images
[AppiumDriver@9e26] Plugin images is now handling cmd 'execute'
[AppiumDriver@9e26] Executing default handling behavior for command 'execute'
[debug] [AndroidUiautomator2Driver@e799 (a5f4b33a)] Encountered internal error running command: NotImplementedError: Method is not implemented
[debug] [AndroidUiautomator2Driver@e799 (a5f4b33a)]     at AndroidUiautomator2Driver.execute (/home/x/.appium/node_modules/appium-uiautomator2-driver/lib/commands/general.js:136:13)
[debug] [AndroidUiautomator2Driver@e799 (a5f4b33a)]     at commandExecutor (/home/x/.nvm/versions/node/v19.8.1/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:107:18)
[debug] [AndroidUiautomator2Driver@e799 (a5f4b33a)]     at /home/x/.nvm/versions/node/v19.8.1/lib/node_modules/appium/node_modules/async-lock/lib/index.js:171:12
[debug] [AndroidUiautomator2Driver@e799 (a5f4b33a)]     at AsyncLock._promiseTry (/home/x/.nvm/versions/node/v19.8.1/lib/node_modules/appium/node_modules/async-lock/lib/index.js:304:31)
[debug] [AndroidUiautomator2Driver@e799 (a5f4b33a)]     at exec (/home/x/.nvm/versions/node/v19.8.1/lib/node_modules/appium/node_modules/async-lock/lib/index.js:170:9)
[debug] [AndroidUiautomator2Driver@e799 (a5f4b33a)]     at AsyncLock.acquire (/home/x/.nvm/versions/node/v19.8.1/lib/node_modules/appium/node_modules/async-lock/lib/index.js:187:3)
[debug] [AndroidUiautomator2Driver@e799 (a5f4b33a)]     at AndroidUiautomator2Driver.executeCommand (/home/x/.nvm/versions/node/v19.8.1/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:123:39)
[debug] [AndroidUiautomator2Driver@e799 (a5f4b33a)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [AndroidUiautomator2Driver@e799 (a5f4b33a)]     at defaultBehavior (/home/x/.nvm/versions/node/v19.8.1/lib/node_modules/appium/lib/appium.js:722:14)
[debug] [AndroidUiautomator2Driver@e799 (a5f4b33a)]     at ImageElementPlugin.handle (/home/x/.appium/node_modules/@appium/images-plugin/lib/plugin.js:75:12)
[debug] [AndroidUiautomator2Driver@e799 (a5f4b33a)]     at /home/x/.nvm/versions/node/v19.8.1/lib/node_modules/appium/lib/appium.js:791:16
[debug] [AndroidUiautomator2Driver@e799 (a5f4b33a)]     at AppiumDriver.executeWrappedCommand (/home/x/.nvm/versions/node/v19.8.1/lib/node_modules/appium/lib/appium.js:828:16)
[debug] [AndroidUiautomator2Driver@e799 (a5f4b33a)]     at AppiumDriver.executeCommand (/home/x/.nvm/versions/node/v19.8.1/lib/node_modules/appium/lib/appium.js:734:17)
[debug] [AndroidUiautomator2Driver@e799 (a5f4b33a)]     at asyncHandler (/home/x/.nvm/versions/node/v19.8.1/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:393:19)

**Comment by mykola-mokhnach** [comment]
Try to put a space after the colon

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-uiautomator2-driver/pull/672 should return the old behaviour
