### ISSUE TITLE
NotImplementedError for performTouch after update to 2.35 version

### ISSUE THREAD

**Issue by superarce** [appium/appium-uiautomator2-driver#701]
I'm working with UiAutomator2 and Kotlin for years and we implemented the swipe action following the code that the appium inspector displayed like:

![Captura de pantalla 2023-12-22 a las 11 43 30](https://github.com/appium/appium-uiautomator2-driver/assets/144555361/003c0601-5c63-418d-9745-26fccaa7f087)

The code in kotlin is like this:

```
  PlatformTouchAction(driver)
  .press(PointOption.point(493, 1360))
  .moveTo(PointOption.point(527, 773))
  .release()
  .perform()

```

Everything has worked fine with UiAutomator2 version 2.17, but after updating the driver to the last version 2.35 we've found a blocker because the driver always returns that the action isn't implemented.

```
[debug] [AndroidUiautomator2Driver@1b7d (eaa514fa)] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":432,"y":1088}},{"action":"moveTo","options":{"x":432,"y":544}},{"action":"release","options":{}}],"eaa514fa-ba77-4d4d-9a1d-5df314ba500b"]
[debug] [AndroidUiautomator2Driver@1b7d (eaa514fa)] Encountered internal error running command: NotImplementedError: Not implemented
[debug] [AndroidUiautomator2Driver@1b7d (eaa514fa)]     at AndroidUiautomator2Driver.swipe (/Users/juan.arceredillo/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/actions.js:48:11)
[debug] [AndroidUiautomator2Driver@1b7d (eaa514fa)]     at AndroidUiautomator2Driver.performTouch (/Users/juan.arceredillo/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/touch.js:226:25)
[debug] [AndroidUiautomator2Driver@1b7d (eaa514fa)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

The point is that we've detected that the action that appium inspector is sending is not the one that is displayed on the app. Our kotlin client sends the previous actions and Appium inspector sends this one:

```
{"actions":[{"type":"pointer","id":"finger1","parameters":{"pointerType":"touch"},"actions":[{"type":"pointerMove","duration":0,"x":500,"y":1567},{"type":"pointerDown","button":0},{"type":"pointerMove","duration":750,"origin":"viewport","x":533,"y":910},{"type":"pointerUp","button":0}]}]}
```

My question is... Is this a bug related to any update from the 2.17 to 2.35 ? 

Thanks in advance

**Comment by KazuCocoa** [comment]
The error itself was expected as the endpoint was deprecated so long.
e.g. https://github.com/appium/java-client/blob/4ab6b5397cc52bc5f078791a91fc0972b3309efa/src/main/java/io/appium/java_client/TouchAction.java#L35-L54

https://github.com/appium/java-client/blob/master/docs/v7-to-v8-migration-guide.md#touch-actions is the migration guide for Java client related to the `TouchAction`

It looks like https://github.com/appium/appium-uiautomator2-driver/blob/master/CHANGELOG.md#2310-2023-10-14 removed that completely by updating the dependencies.

**Comment by superarce** [comment]
Hi @KazuCocoa ,

I haven't realized of that deprecation. I'm using the java client 7.6 at the moment.
I'm going to migrate all my actions to the new W3C API in order to be allowed to update the drivers.

Thanks you
