### ISSUE TITLE
Appium does not work.

### ISSUE THREAD

**Issue by openSourceBugs** [appium/appium-uiautomator2-driver#756]
https://appium.io/docs/en/latest/quickstart/uiauto2-driver/  following this tutorial I get:
Original error: Could not find a driver for automationName 'uiautomator2' and platformName 'Android'. Have you installed a driver that supports those capabilities? 

capabilities are:

capabilities = dict(
    platformName='Android',
    automationName='uiautomator2',
    deviceName='Android',
    appPackage='com.android.settings',
    appActivity='.Settings',
    language='en',
    locale='US'
)

driver installed:

appium driver list --installed
√ Listing installed drivers
- uiautomator2@3.0.4 [installed (npm)]

If this doesn't work from the very beginning, the whole thing is broken.

**Comment by openSourceBugs** [comment]
Instead of saying the server was never started, it complains that the driver wasn't installed, which is completely the wrong thing to do.

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by eglitise** [comment]
Closing due to no response
