### ISSUE TITLE
cannot install uiautomator2 driver

### ISSUE THREAD

**Issue by klreeher** [appium/appium-uiautomator2-driver#762]
I am setting up Appium on a new machine, and running into issues installing the uiautomator2 driver. I'm on Windows.

NPM Version: 10.5.0
APPIUM VERSION: 2.5.2

When I attempt to run `appium driver install uiautomator2` I get the following error:

```
Error: npm command 'info appium-uiautomator2-driver peerDependencies dependencies --json' failed with code EINVAL.

STDOUT:


STDERR:
```

Not super helpful. If i run that command on its own:

```
PS C:\Users\kreeher> npm info appium-uiautomator2-driver peerDependencies dependencies --json
{
  "peerDependencies": {
    "appium": "^2.4.1"
  },
  "dependencies": {
    "appium-adb": "^12.0.0",
    "appium-android-driver": "^9.1.0",
    "appium-chromedriver": "^5.6.28",
    "appium-uiautomator2-server": "^7.0.1",
    "asyncbox": "^3.0.0",
    "axios": "^1.6.5",
    "bluebird": "^3.5.1",
    "css-selector-parser": "^3.0.0",
    "io.appium.settings": "^5.7.2",
    "lodash": "^4.17.4",
    "portscanner": "^2.2.0",
    "source-map-support": "^0.x",
    "teen_process": "^2.0.0",
    "type-fest": "^4.4.0"
  }
}
```

I did attempt to install the driver sepretely, via npm --

` npm install appium-uiautomator2-driver ` installs just fine. 

```
PS C:\Users\kreeher> npm list appium-uiautomator2-driver
kreeher@ C:\Users\kreeher
`-- appium-uiautomator2-driver@3.1.0
``` 

No change when I try to install for appium again. 

Any thoughts?

**Comment by KazuCocoa** [comment]
It looks like https://github.com/appium/appium/pull/19996 fixes this. It is not released yet but you could use the appium repository directly

**Comment by klreeher** [comment]
@KazuCocoa  thanks for the information! the fix linked to a thread, which had a manual overwrite. Got me up and running. I would also appreciate knowing what the eta is, if there is one.

**Comment by KazuCocoa** [comment]
There is no guaranteed ETA, but I assume it's not so late. (I guess in a few days or so)

**Comment by KazuCocoa** [comment]
I think the latest is fine
