### ISSUE TITLE
appium driver install uiautomator2 Installation error

### ISSUE THREAD

**Issue by wholegale39** [appium/appium-uiautomator2-driver#763]
PS C:\Users\wch> node -v
v18.20.2
PS C:\Users\wch> npm -v
10.5.0
PS C:\Users\wch.xdja> appium -v
2.0.0
PS C:\Users\wch> appium driver install uiautomator2
✖ Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: ✖ Encountered an error when installing package: npm command 'install --save-dev --no-progress --no-audit --omit=peer --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code EINVAL.

STDOUT:

STDERR:

or

PS C:\Users\wch.xdja> appium -v
2.5.2
PS C:\Users\wch.xdja>
PS C:\Users\wch.xdja>
PS C:\Users\wch.xdja> appium driver install uiautomator2
✖ Checking if 'appium-uiautomator2-driver' is compatible
Error: npm command 'info appium-uiautomator2-driver peerDependencies dependencies --json' failed with code EINVAL.

STDOUT:

STDERR:

I have tried other versions, and the above problems will also occur

**Comment by mykola-mokhnach** [comment]
Check https://discuss.appium.io/t/appium-driver-install-fails-while-checking-drivers-compatibility/42209

**Comment by wholegale39** [comment]
It works, thank you so much!
