### ISSUE TITLE
× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'

### ISSUE THREAD

**Issue by yuanshirenasdas24525** [appium/appium-uiautomator2-driver#764]
![image](https://github.com/appium/appium-uiautomator2-driver/assets/150315853/45bac465-1f5b-40d6-90fc-1baf368b5db2)
![image](https://github.com/appium/appium-uiautomator2-driver/assets/150315853/19ed0405-e877-4b27-add8-239a89ee38a5)
![image](https://github.com/appium/appium-uiautomator2-driver/assets/150315853/ce285cd6-c279-43f1-80a8-fbaea90db81a)

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/20014 the same post
