### ISSUE TITLE
Appium inspector checks that some labels do not have text information. How to get it?

### ISSUE THREAD

**Issue by jepson66** [appium/appium-uiautomator2-driver#768]
I would like to ask, some labels do not have text attributes, but there is text, but the elements captured through appium inspector are as follows. 

 
<img width="1035" alt="image" src="https://github.com/appium/appium-uiautomator2-driver/assets/108441697/a60f4cf1-ae64-4518-835c-0526e5bfa153">

Where does this text content come from? How should I get it? Anyone who knows can please answer it. ?

**Comment by mykola-mokhnach** [comment]
these properties are retrieved from the accessibility information that the destination view provides to the system. Read https://developer.android.com/training/testing/other-components/ui-automator for more details

**Comment by jepson66** [comment]
@KazuCocoa tanks for you！I tring it
