### ISSUE TITLE
Please apply this func - https://github.com/appium/appium-adb/pull/739

### ISSUE THREAD

**Issue by msochacki** [appium/appium-uiautomator2-driver#776]
Hi, 
Please apply this functionality 
 https://github.com/appium/appium-adb/pull/739 
to pass userProfile id.

**Comment by KazuCocoa** [comment]
We're preparing in proper way https://github.com/appium/appium-android-driver/pull/932

**Comment by KazuCocoa** [comment]
You could try out https://github.com/appium/appium-uiautomator2-driver/pull/778
