### ISSUE TITLE
`mobile: stopService` throws WebDriverException

### ISSUE THREAD

**Issue by nichiyoshi** [appium/appium-uiautomator2-driver#792]
# Issue
I am trying to stop the service of `io.appium.settings/.LocationService` using the `executeScript("mobile: stopService")`, but it throws WebDriverException as follows.

Code
```
val params = mapOf(
        "intent" to "io.appium.settings/.LocationService"
    )

runCatching { appiumDriver.executeScript("mobile: stopService", params) as String }
            .fold(
                onSuccess = { result -> CommandResult.Success(result) },
                onFailure = { exception -> CommandResult.Exception(exception) }
            )
```
Exception log
```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'path-to-adb -P 5037 shell am stop-service io.appium.settings/.LocationService' exited with code 255'; Command output: Service stopped
```

This also happens when I execute the same with `executeScript("mobile: shell")`

Code
```
val params =
          mapOf(
              "command" to "am stopservice io.appium.settings/.LocationService",
          )

return runCatching { appiumDriver.executeScript("mobile: shell", params) as String }
  .fold(
      onSuccess = { result -> CommandResult.Success(result) },
      onFailure = { exception -> CommandResult.Exception(exception) }
  )
```

Exception log
```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot execute the 'am stopservice io.appium.settings/.LocationService' shell command. Original error: Command 'path-to-adb -P 5037 shell 'am stopservice io.appium.settings/.LocationService'' exited with code 255. StdOut: Stopping service: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=io.appium.settings/.LocationService }
. StdErr: Service stopped
```

If I just run adb command from terminal, it succeeds.
-> It turned out it was returning 255, and the message was output to `inputstream` of the `Process`, not the `errorStream`
```
% adb shell am stopservice io.appium.settings/.LocationService 
Stopping service: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=io.appium.settings/.LocationService }
Service stopped

```

**Comment by KazuCocoa** [comment]
What was the exit code in the adb shell?

It looks like https://github.com/appium/appium-android-driver/blob/7532ad4d1680b1dd661b55bd3958b6205c47c7f3/lib/commands/intent.js#L155-L166 should handle if the command succeeds by checking the output

**Comment by mykola-mokhnach** [comment]
I assume it's an issue with the adb itself. Ideally it should return the exit code 0 in case of a successful response. Let me add a a workaround for now :(

**Comment by nichiyoshi** [comment]
> I assume it's an issue with the adb itself. Ideally it should return the exit code 0 in case of a successful response. Let me add a a workaround for now :(

Thank you for the quick workaround to fix this!
Yes, it seems the issue is of the adb itself. According to logs, I could confirm that it started to happen around the 7th June.

**Comment by KazuCocoa** [comment]
UIA2 driver `3.5.4` has the fix
