### ISSUE TITLE
Setting 'disableIdLocatorAutocompletion' is not supported

### ISSUE THREAD

**Issue by testingmobileat** [appium/appium-uiautomator2-driver#802]
Hi everyone,
I  tried to update appium settings in my capabilities
`'appium:settings[disableIdLocatorAutocompletion]': true,`
and also tried this,
`driver.updateSettings({ 'appium:disableIdLocatorAutocompletion': true })`
 Always got the error 

> "Setting 'disableIdLocatorAutocompletion' is not supported."
![image](https://github.com/appium/appium-uiautomator2-driver/assets/174785984/72259cfb-fdd5-4339-9155-720035e36420)

But when using the appium inspector it works.

**Comment by KazuCocoa** [comment]
Please attach the full appium server log.

**Comment by testingmobileat** [comment]
@KazuCocoa This is the full log, i'm running in browserstack, I'm not sure this issue from appium or from browserstack.
[log.txt](https://github.com/user-attachments/files/16118897/log.txt)
Thank you for helping me.

**Comment by KazuCocoa** [comment]
It is not appium server log. Please ask the BS customer support to get the full appium server log if you don't the way. I assume they customize that, or their running UA2 driver is old.

**Comment by testingmobileat** [comment]
Ok thank you, i will ask them.
For now I will close this issue
