### ISSUE TITLE
[Chrome] The elements on web site couldn't be locate as NATIVE_APP on Android

### ISSUE THREAD

**Issue by shipingyuan** [appium/appium-uiautomator2-driver#833]
Hi Appium Uiautomator2 Team,

The elements on our test site couldn't be able to locate on Native context, the web site is displayed as a android.webkit.WebView from insepector and have no any child elements.
(**BTW, this issue only merges after upgrading Android OS and chrome, it worked fine before.**)
<img width="1567" alt="Screen Shot 2024-10-25 at 15 09 49" src="https://github.com/user-attachments/assets/59be5f56-e2ce-49f4-95d9-5792bad9faad">

If switch context to WebView, the find element methods don't work with below error:
`_Got response with status 400: {"value":{"error":"invalid argument","message":"invalid argument: invalid locator\n  (Session info: chrome=129.0.6668.100)","stacktrace":"\tGetHandleVerifier [0x00007FF66952B095+29557]\n\t(No symbol) [0x00007FF66949FA50]\n\t(No symbol) [0x00007FF66935B56A]\n\t(No symbol) [0x00007FF6693AEE02]\n\t(No symbol) [0x00007FF6693AF8EC]\n\t(No symbol) [0x00007FF6693FB7A7]\n\t(No symbol) [0x00007FF6693D71CF]\n\t(No symbol) [0x00007FF6693F851C]\n\t(No symbol) [0x00007FF6693D6F33]\n\t(No symbol) [0x00007FF6693A116F]\n\t(No symbol) [0x00007FF6693A22D1]\n\tGetHandleVerifier [0x00007FF66985C96D+3378253]\n\tGetHandleVerifier [0x00007FF6698A8497+3688311]\n\tGetHandleVerifier [0x00007FF66989D1CB+3642539]\n\tGetHandleVerifier [0x00007FF6695EA6B6+813462]\n\t(No symbol) [0x00007FF6694AAB5F]\n\t(No symbol) [0x00007FF6694A6B74]\n\t(No symbol) [0x00007FF6694A6D10]\n\t(No symbol) [0x00007FF669495C1F]\n\tBaseThreadInitThunk [0x00007FFB481D257D+29]\n\tRtlUserThreadStart [0x00007FFB494EAF28+40]\n"}}_`

<img width="560" alt="Screen Shot 2024-10-25 at 15 21 27" src="https://github.com/user-attachments/assets/2cf493e3-1040-492f-8341-f0f8f581adc5">

### [Test env]
**Android:**
Device: Galaxy S23+ (Android 14)
Browser:  Chrome 129.0.6668.100

**Capability:**
```
{
  "appium:platformName": "Android",
  "appium:deviceName": "R3CW10GYZXX",
  "appium:automationName": "uiautomator2",
  "appium:appPackage": "com.android.chrome",
  "appium:appActivity": "com.google.android.apps.chrome.Main",
  "appium:noReset": true
}
```

**Appium server:**
<img width="1041" alt="Screen Shot 2024-10-25 at 15 31 44" src="https://github.com/user-attachments/assets/852a9f72-9ff6-4a2c-b4bd-af226f6e694c">

**Comment by mykola-mokhnach** [comment]
The above error is returned by chromedriver itself. I don't know how we could help there.
Also, the full server log is missing.

**Comment by shipingyuan** [comment]
Thanks.
I am more concerned about the first question:
The elements on our test site couldn't be able to locate as NATIVE_APP, it is always displaying as a WebView.
(BTW, this issue only merges after upgrading Android OS and chrome, it worked fine before.)

How to find the elements as NATIVE_APP?

**Comment by mykola-mokhnach** [comment]
> How to find the elements as NATIVE_APP?

Not sure what you mean there. In the above log I see findElement(s) API being called in native context without any issues. You may also check https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#elements-cannot-be-found

**Comment by shipingyuan** [comment]
I means that the elements on our test web site are now not found in native context. Our all cases on Android client are based on native context, so these case are blocked by this issue. Before upgrading Andriod and Chrome Brower, these cases were passed.
I want to find the root cause to resolve this issue, but have no clue.

**Comment by KazuCocoa** [comment]
Elements info in NATIVE_APP depends on what info the Android OS returns as https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo . Some WebView contents could be detected in NATIVE_APP as part of native elements since Android OS handled so, but the behavior depends on the OS side.

What Appium could provide is the above mykola's comment. I saw that some users succeeded in finding webview elements with ignoreUnimportantViews but some were not, needed to switch to WEBVIEW context.

**Comment by mykola-mokhnach** [comment]
I remember seeing an issue once in Chromedriver bugtracker related to how accessibility rendering happens. Basically, after some version of it the team did some optimizations, so Chrome stopped to render web page elements as accessible and the only way to interact with them is to switch from native to a web context. Unfortunately, like I said above, we cannot influence this process.

**Comment by shipingyuan** [comment]
Thanks for your help. I plan to switch to webview from native.
