### ISSUE TITLE
Issues with screenshotting in the latest version

### ISSUE THREAD

**Issue by Nick-qa-dev** [appium/appium-uiautomator2-driver#837]
When I execute this command on Android it outputs the complete base64 for the screenshot to the console. Could we have a silent option so that it doesn't output ten thousand lines to the console. It looks like this is implemented for screenshots

const viewScreen = await driver.execute("mobile: viewportScreenshot", [
      {
        arg1: "0",
      },
    ])

Cheers
Nick

**Comment by eglitise** [comment]
Closing due to no response
