### ISSUE TITLE
Doc Link for Automating hybrid apps is broken. 

### ISSUE THREAD

**Issue by kesavarao-EB** [appium/appium-uiautomator2-driver#840]
[Automating hybrid apps](https://github.com/appium/appium-uiautomator2-driver/blob/1c569812f52968953e7ecae4cd54feac1ff4314c/docs/activity-startup.md)

Automating hybrid apps -> link is misleading to activity-startup page.

**Comment by KazuCocoa** [comment]
Updated the link to https://github.com/appium/appium-uiautomator2-driver/blob/master/README.md#hybrid-mode 
Perhaps the original one was removed in the past.
