### ISSUE TITLE
Multiple Windows in the Android tablet APP, the left page cannot be recognized

### ISSUE THREAD

**Issue by cchwasd** [appium/appium-uiautomator2-driver#841]
** Multiple Windows in the Android tablet APP, the left page cannot be recognized, and control elements are obtained

For example, Settings APP page

But python uiautomator2 can recognize it

**Comment by mykola-mokhnach** [comment]
Have you tried [enableMultiWindows setting](https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#settings-api)?

**Comment by cchwasd** [comment]
![image](https://github.com/user-attachments/assets/ce2094df-b3b5-4b7b-bad0-a1369df7f502)

The left side of the Android tablet

**Comment by cchwasd** [comment]
Thank you very much
